{{- if .Values.gatewayAPI.httpRoute.enabled -}}
{{- $fullName := include "oauth2-proxy.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
  {{- with .Values.gatewayAPI.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  {{- with .Values.gatewayAPI.httpRoute.parentRefs }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostnames:
  {{- with .Values.gatewayAPI.httpRoute.hostnames }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  {{- if .Values.gatewayAPI.httpRoute.rules }}
    {{- toYaml .Values.gatewayAPI.httpRoute.rules | nindent 4 }}
  {{- else }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $fullName }}
          port: 4180
  {{- end }}
{{- end }}
