{{- $fullName := include "oauth2-proxy.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
type: Opaque
stringData:
  client-id: "{{ .Values.secret.clientId }}"
  client-secret: "{{ .Values.secret.clientSecret }}"
  cookie-secret: "{{ .Values.secret.cookieSecret }}"
